ARG SOURCEIMAGE
FROM ${SOURCEIMAGE}

USER root

RUN rm -rf ${TEMP_DIR} && mkdir -p ${TEMP_DIR}

COPY modules ${TEMP_DIR}/modules

RUN cd ${TEMP_DIR}/modules/gar && \
    mvn clean install && \
    cd ${TEMP_DIR}/modules && \
    mvn clean install

RUN chown -R oracle:oracle ${TEMP_DIR}/ && \
    chmod -R a+xwr ${TEMP_DIR}/

WORKDIR ${DOMAIN_HOME}
